baseURL = "https://blog.reizist.com/"
languageCode = "en-us"
title = "reizist's memo"
theme = "purehugo"
Paginate = 5
disqusShortname = "reizist"
google_analytics = "UA-128918318-1"

[params]
  twitter = "reizist"
  twitterName = "reizist"
  githubName = "reizist"
  stackOverflowId = "8758262"
  description = "reizist's daily memo"