baseURL = "https://blog.reizist.com/"
languageCode = "jp"
title = "reizist's memo"
theme = "github-style"
Paginate = 5
disqusShortname = "reizist"
google_analytics = "UA-128918318-1"

[params]
  twitter = "reizist"
  twitterName = "reizist"
  twitterCardType = "summary_large_image"
  githubName = "reizist"
  stackOverflowId = "8758262"
  stackoverflow = "8758262"
  description = "reizist's daily memo"
  avatar = "https://blog.reizist.com/images/avatar.png"

  author = "reizist"
  github = "reizist"
  instagram = "reizist7"
  rss = true
  url = "https://twitter.com/reizist"
  lastmod = false
