baseURL = "https://blog.reizist.com/"
languageCode = "jp"
title = "reizist's memo"
theme = "my-github-style"
Paginate = 5
disqusShortname = "reizist"
googleAnalytics = "G-9SW1WXQHM8"

[params]
  amazonJpAffiliate = "reiji012-22"
  twitter = "reizist"
  twitterName = "reizist"
  githubName = "reizist"
  stackOverflowId = "8758262"
  stackoverflow = "8758262"
  description = "reizist's daily memo"
  avatar = "https://blog.reizist.com/images/avatar.png"

  uthor = "reizist"
  github = "reizist"
  instagram = "reizist7"
  rss = true
  url = "https://twitter.com/reizist"
  lastmod = false
