version: 2.1

orbs:
  build-push: reizist/hugo-build-push@dev:8

workflows:
  "build-push":
    jobs:
      - build-push/build:
          filters:
            branches:
              only:
                - $GIT_BUILD_BRANCH