version: 2.1

orbs:
  hugo: circleci/hugo@0.4.1

jobs:
  deploy:
    docker:
      - image: reizist/alpine-hugo
    steps:
      - attach_workspace:
          at: blog-reizist-com
      - run: ls -lah blog-reizist-com

workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: false
          version: '0.55'
      - deploy:
          filters:
            branches:
              only: develop
          requires:
            - hugo/build
