version: 2
jobs:
  build:
    docker:
      - image: reizist/alpine-hugo

    working_directory: ~/hugo
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: git config
          command: |
              git config --global user.name "reizist"
              git config --global user.email "reizist@gmail.com"
      - run:
          name: git sync
          command: |
              git submodule init
              git submodule update
              git init public
              cd public
              git checkout -b gh-pages
              git remote add origin "git@github.com:reizist/reizist.github.io.git"
              cd ..
      - run:
          name: build and push
          command: |
              hugo
              cp -prv .circleci public
              cd public
              git add .
              git commit -m "[ci skip] publish"
              git push -f origin gh-pages
